# -------------------------------------------------------------------------
# TESTING PROFILE CONFIGURATION
# -------------------------------------------------------------------------
# Create schema from scratch and drop it when context closes
spring.jpa.hibernate.ddl-auto=create-drop

# Show SQL queries
spring.jpa.show-sql=true

# Typically, you would override the database URL here to point to an H2 in-memory DB
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=