# -------------------------------------------------------------------------
# PRODUCTION PROFILE CONFIGURATION
# -------------------------------------------------------------------------
# NEVER use 'update' or 'create' in production. Use 'validate' or 'none'.
# Database migrations should be handled by Liquibase/Flyway.
# Temporarily set to 'update' to automatically create missing tables on first deployment.
spring.jpa.hibernate.ddl-auto=update

# Disable SQL logging to save logs and improve performance
spring.jpa.show-sql=false

# Enable caching
spring.template.cache=true

# Logging Level
logging.level.root=WARN
logging.level.com.anvistudio.boutique=INFO